[package]
name = "cairo_template"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
openzeppelin = "0.18.0"
alexandria_encoding = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "7c19379ab6cf0f8b48be3c5b118ffddd7e26a4d2" }
graffiti = { git = "https://github.com/ponderingdemocritus/graffiti", rev = "bc569531791dbc71c6cd8d9bc154c34eedad31fe" }

[dev-dependencies]
cairo_test = "2.8.4"

[[target.starknet-contract]]
casm = true
